import React from "react";

export const metadata = {
  title: "About Our Website",
  // description: "Generated by create next app",
};

export default function About() {
  return <div>About</div>;
}
