import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen bg-zinc-900 text-zinc-100 font-bold items-center justify-center text-4xl`}
      >
        {children}
      </body>
    </html>
  );
}
